# IMPORT DEPENDENCIES

In [1]:
pip install transformers 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.4 MB 5.1 MB/s 
     |████████████████████████████████| 101 kB 10.8 MB/s 
     |████████████████████████████████| 596 kB 48.1 MB/s 
     |████████████████████████████████| 6.6 MB 26.9 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
pip  install beautifulsoup4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch


# MODEL

In [4]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

Downloading:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/953 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/851k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/638M [00:00<?, ?B/s]

# CALCULATE SENTIMENT

In [5]:
tokens=tokenizer.encode('Well, I kinda hate to admit it but I like going to Apple Bees. I enjoy the atmosphere (louder than average) sports theme with reasonable prices. Drink and appetizers specials during football season (I am a huge fan). But this location is off the Hook! Views, service, food is great, love it!',return_tensors='pt')

In [6]:
tokens

tensor([[  101, 11327,   117,   151, 16540, 10112, 39487, 10114, 10816, 16378,
         10197, 10502,   151, 11531, 17010, 10114, 17006, 33848,   119,   151,
         61530, 10103, 37376,   113, 59399, 10177, 10948, 11237,   114, 13374,
         18245, 10171, 23065, 13356, 50791,   119, 49755, 10110, 35821, 15267,
         76844, 11999, 10107, 10770, 11420, 11286,   113,   151, 10345,   143,
         37985, 10923,   114,   119, 10502, 10372, 17900, 10127, 11856, 10103,
         27702,   106, 29793,   117, 11416,   117, 15225, 10127, 11838,   117,
         11157, 10197,   106,   102]])

In [7]:
result=model(tokens)

In [8]:
result

SequenceClassifierOutput([('logits',
                           tensor([[-3.1141, -1.8119,  0.6456,  2.1947,  1.5070]],
                                  grad_fn=<AddmmBackward0>))])

In [9]:
result.logits

tensor([[-3.1141, -1.8119,  0.6456,  2.1947,  1.5070]],
       grad_fn=<AddmmBackward0>)

In [10]:
int(torch.argmax(result.logits))+1

4